
services:
  db:
    image: postgres:15-alpine
    container_name: bimarz_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bimarz_db
      POSTGRES_USER: bimarz_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - bimarz_network
    # Only accessible within the Docker network
    expose:
      - "5432"

  redis:
    image: redis:7-alpine
    container_name: bimarz_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass X%k0c2t3o7
    volumes:
      - redis_data:/data
    networks:
      - bimarz_network
    # Only accessible within the Docker network
    expose:
      - "6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=bimarz_db
      - DB_USER=bimarz_user
      - DB_PASSWORD= ${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://${REDIS_PASSWORD}@redis:6379/0
      - ALLOWED_HOSTS=backend,localhost,127.0.0.1,bimarz.org,www.bimarz.org,vps_ip_address
      - DOCKER_ENV=True
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - bimarz_network
    # Only accessible within the Docker network
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://bimarz.org/api
    depends_on:
      - backend
    networks:
      - bimarz_network
    # Only accessible within the Docker network
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: bimarz_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - static_volume:/var/www/static:ro
      - media_volume:/var/www/media:ro
    depends_on:
      - frontend
      - backend
    networks:
      - bimarz_network

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  bimarz_network:
    driver: bridge
